import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import BodySample from './bodySample'
import SubTitleSample from './subTitleSample'
import FeatureSections from './featureSection'
import BigNews from './bigNews'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a>itdepends.tech</a> !
        </h1>
        <h1 className={styles.title}>
        
          your <a> fit  </a> tech stack
        </h1>
        {/* <FeatureSections></FeatureSections> */}
        <BodySample></BodySample>
        <SubTitleSample></SubTitleSample>
      </main>

      {/* <footer className={styles.footer}>
        <div class="py-8 px-8 max-w-sm mx-auto bg-white rounded-xl shadow-lg space-y-2 sm:py-4 sm:flex sm:items-center sm:space-y-0 sm:space-x-6">
          <img class="block mx-auto h-24 rounded-full sm:mx-0 sm:shrink-0" src="/oussama-akir.jpg" alt="Woman's Face" />
          <div class="text-center space-y-2 sm:text-left">
            <div class="space-y-0.5">
              <p class="text-lg text-black font-semibold">
                Akir Oussama
              </p>
              <p class="text-slate-500 font-medium">
                Frontend Developer && Problem Solver
              </p>
            </div> </div>
        </div>
      </footer> */}
    </div >
  )
}
