import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a>itdepends.tech ! your fit tech stack </a>
        </h1>
        <h1 className={styles.title}>
          your <a> fit  </a> tech stack
        </h1>
        <h1 className="text-3xl font-bold underline">
          Hello world!
        </h1>
        <p className={styles.description}>
          Ready to build a software product?
          Choosing the right tech stack will ensure a cost-efficient and successful development project.
        </p>

        <div className={styles.grid}>
          <a href="https://www.itdepends.tech/" className={styles.card}>
            <h2>What іs a Technology Stack? &rarr;</h2>
            <p>A tech stack refers to a set of tools, programming languages,
              and technologies that work together to build digital products
              or solutions such as websites, mobile, and web apps.</p>
          </a>

          <a href="https://www.itdepends.tech/" className={styles.card}>
            <h2>How to Choose a Technology Stack? &rarr;</h2>
            <p>Tech stack is consequential because it’s what you use for creating software programs.
              Thus, don’t underestimate the essence of research and analysis to select the right set of tools.</p>
          </a>

          <a
            href="https://www.itdepends.tech/"
            className={styles.card}
          >
            <h2>Top Tech Stack Models &rarr;</h2>
            <p>To save you time and money, you can use proven tech stack models.</p>
          </a>

          <a
            href="https://www.itdepends.tech/"
            className={styles.card}
          >
            <h2>Get Expert Help &rarr;</h2>
            <p>
              If you’re not trained in web development, then leave it to the experts.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
      
      </footer>
    </div>
  )
}
